<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{

    public function run()
    {
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'VOL-0721-10',
            'nombre' => 'Carroceria de redilla cerrada',
            'presentacion' => 'Pza',
            'stock' => '10',
            'dimension' => '2.3M',
            'preciodistribuidor' => '3515479',
            'preciocontado' => '3707232',
            'preciopublico' => '3898984',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 2,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'VOL-0721',
            'nombre' => 'Carrocerias tipo estacas',
            'presentacion' => 'Pza',
            'stock' => '10',
            'dimension' => '3.5M',
            'preciodistribuidor' => '2273498',
            'preciocontado' => '2400530',
            'preciopublico' => '252492',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 2,
            'descripcion' => 'Producto en piso de venta',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'VOL-0721',
            'nombre' => 'Plataformas',
            'presentacion' => 'Pza',
            'stock' => '3',
            'dimension' => '2.3M',
            'preciodistribuidor' => '2398770',
            'preciocontado' => '2529512',
            'preciopublico' => '25504',
            'imagen' => 'imagen',
            'categorias_id' => 2,
            'estatus_id' => 2,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'VOL-0721',
            'nombre' => 'Cajas secas',
            'presentacion' => 'Pza',
            'stock' => '1',
            'dimension' => '2.3M',
            'preciodistribuidor' => '7077012',
            'preciocontado' => '5408421',
            'preciopublico' => '5789958',
            'imagen' => 'imagen',
            'categorias_id' => 2,
            'estatus_id' => 2,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'PLA-0821',
            'nombre' => 'Plataforma chica',
            'presentacion' => 'Pza',
            'stock' => '7',
            'dimension' => '2.3M',
            'preciodistribuidor' => '1058451',
            'preciocontado' => '10034134',
            'preciopublico' => '111284878',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 2,
            'descripcion' => 'Producto de planta',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
         DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'CAJ-08-21',
            'nombre' => 'Caja seca grande',
            'presentacion' => 'Pza',
            'stock' => '9',
            'dimension' => '5 M',
            'preciodistribuidor' => '15258287',
            'preciocontado' => '17155478',
            'preciopublico' => '18043012',
            'imagen' => 'imagen',
            'categorias_id' => 2,
            'estatus_id' => 1,
            'descripcion' => 'Producto en produccion',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'Volteos',
            'nombre' => 'Volteos de todas las medidas',
            'presentacion' => 'Pza',
            'stock' => '1',
            'dimension' => '2.3M',
            'preciodistribuidor' => '55000',
            'preciocontado' => '55000',
            'preciopublico' => '2587',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 2,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'Volteos',
            'nombre' => 'Volteos de todas las medidas',
            'presentacion' => 'Pza',
            'stock' => '8',
            'dimension' => '2.3M',
            'preciodistribuidor' => '55000',
            'preciocontado' => '55000',
            'preciopublico' => '2587',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 2,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'Volteos',
            'nombre' => 'Volteos de todas las medidas',
            'presentacion' => 'Pza',
            'stock' => '7',
            'dimension' => '2.3M',
            'preciodistribuidor' => '55000',
            'preciocontado' => '55000',
            'preciopublico' => '2587',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 1,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'Vol-21',
            'nombre' => 'Volteos de todas las medidas',
            'presentacion' => 'Pza',
            'stock' => '2',
            'dimension' => '2.3M',
            'preciodistribuidor' => '55000',
            'preciocontado' => '55000',
            'preciopublico' => '2587',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 1,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);

        DB::table('productos')->insert([
            'tipoproducto' => 'Producto comercial',
            'clave' => 'Pip-20',
            'nombre' => 'Pipa de 20,000 lts',
            'presentacion' => 'Pza',
            'stock' => '1',
            'dimension' => '2.3M',
            'preciodistribuidor' => '55000',
            'preciocontado' => '55000',
            'preciopublico' => '2587',
            'imagen' => 'imagen',
            'categorias_id' => 1,
            'estatus_id' => 2,
            'descripcion' => 'Producto terminado',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
    }
}
